name: Swinject
options:
  bundleIdPrefix: com.el-eleven
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  deploymentTarget:
    macOS: '10.13'
    tvOS: '12.0'
    iOS: '12.0'
    watchOS: '4.0'
    visionOS: '1.0'
fileGroups:
  - Playgrounds/Sample-iOS.playground
targets:
  Swinject:
    type: framework
    platform: [macOS, iOS, tvOS, watchOS, visionOS]
    platformSuffix: -${platform}
    settings:
      base:
        APPLICATION_EXTENSION_API_ONLY: 'YES'
        BUILD_LIBRARY_FOR_DISTRIBUTION: 'YES'
        RUN_DOCUMENTATION_COMPILER: 'YES'
    scheme:
      testTargets:
        - SwinjectTests-${platform}
    sources:
      - path: Sources
        excludes: ["*.erb"]
  SwinjectTests:
    type: bundle.unit-test
    platform: [macOS, iOS, tvOS, watchOS, visionOS]
    platformSuffix: -${platform}
    scheme: {}
    sources:
      - Tests/SwinjectTests
    dependencies:
      - target: Swinject-${platform}
